apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
data:
  jwt.secret: "*V)zNZJG2gVyxA_4$Q_C7^)qrSdDDk0tW"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: mail-config
data:
  host: smtp.example.com
  port: "587"
---
apiVersion: v1
kind: Secret
metadata:
  name: mail-credentials
type: Opaque
data:
  username: base64-encoded-username
  password: base64-encoded-password
---
apiVersion: v1
kind: Secret
metadata:
  name: minio-credentials
type: Opaque
data:
  access-key: base64-encoded-access-key
  secret-key: base64-encoded-secret-key 